apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi