apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: statefulset-ns
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo
    tier: backend
  type: NodePort