# 
version: "2"
# 
services:
  # 
  item-app:
    # 
    image: riotryulianto/item-app:v1
    # 
    ports:
      - 80:8080
    # 
    restart: on-failure
  # 
  item-db:
    # 
    image: mongo:3
    # 
    volumes:
      - app-db:/data/db
    # 
    restart: on-failure
# 
volumes:
  app-db:
