apiVersion: v1
kind: Deployment
metadata:
  name: karsajobs-deployment
  labels:
    app: backend
spec:
  containers:
  - name: karsajobs
    image: riotryulianto/karsajobs:latest
    env:
    - name: APP_PORT
      value: "8080"
    - name: MONGO_HOST
      value: mongo-service
    - name: MONGO_USER
      value: MONGO_ROOT_USERNAME
    - name: MONGO_PASS
      value: MONGO_ROOT_PASSWORD
    ports:
      - containerPort: 80