apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: microservices
        tier: app
    spec:
      containers:
      - name: karsajobs
        image: riotryulianto/karsajobs:latest
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_USER
          value: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          value: MONGO_ROOT_PASSWORD
        ports:
          - containerPort: 80