apiVersion: v1
kind: Pod
metadata:
  name: karsajobs-deployment
  labels:
    app: backend
spec:
  containers:
  - name: karsajobs
    image: riotryulianto/karsajobs:latest
    resources:
      requests:
        memory: "128Mi" # 128Mi = 128 mebibytes
        cpu: "500m"     # 500m = 500 milliCPUs (1/2 CPU)
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80