apiVersion: v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  labels:
    app: frontend
spec:
  containers:
  - name: karsajobs-ui
    image: riotryulianto/karsajobs-ui:latest
    ports:
      - containerPort: 80