apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: support
  template:
    metadata:
      labels:
        app: microservices
        tier: support
    spec:
      containers:
      - name: karsajobs-ui
        image: riotryulianto/karsajobs-ui:latest
        ports:
          - containerPort: 80